### ISSUE TITLE
ReferenceError: require is not defined (line 1, col 9)

### ISSUE THREAD

**Issue by adamgins** [ntsaini/node-red-contrib-function-npm#10]
Hi, I am getting `ReferenceError: require is not defined (line 1, col 9)` 

My code in a `function` node is `var _ = require('lodash');` 

I installed lodash with `npm i --save lodash`

My directory that I have Node Red running locally shows

![screen shot 2018-12-27 at 5 10 32 pm](https://user-images.githubusercontent.com/7233741/50468257-ed58bb00-09fa-11e9-920e-8d0971809abd.png)

Node red version `0.19.5`

**Comment by ntsaini** [comment]
You don't need to install loadash separately. The function-npm node will install it automatically. Make sure you are using the function-npm node and not the built in function node.

Also, from the screenshot seems like your installation of the module is not quite correct. The node-red modules needs to be installed in node-red directory. Please look at the following documentation link from node-red website [https://nodered.org/docs/getting-started/adding-nodes](https://nodered.org/docs/getting-started/adding-nodes)

**Comment by ntsaini** [comment]
no response. closing
