### ISSUE TITLE
Incorrect dir lookup for node modules installed from github

### ISSUE THREAD

**Issue by layoutanalysis** [ntsaini/node-red-contrib-function-npm#12]
**Reproduce:**
1. Create "function npm" node with the following code
`var getCSS = require('layoutanalysis/get-css');`
2. Deploy Workflow

**Expected Behaviour**
Workflow gets deployed without error, require'd module can be used in code.

**Actual Behaviour:**
Error during deploy:
`Error: Cannot find module 'C:\Users\gamingpc\AppData\Local\Temp\d-11912-8448-14iletx.vc6e/node_modules/layoutanalysis/get-css'`

**Remark**
module code gets installed correctly to ...node_modules/get-css,  but function-npm looks in ...node_modules/layoutanalysis/get-css

**Comment by ntsaini** [comment]
@layoutanalysis Thanks for leaving a detailed description of the error. I think i understand why it is happening. I will take a look into it and try to push out an update soon.

**Comment by ntsaini** [comment]
@layoutanalysis  Fixed the issue in the new release. Try it out.

**Comment by layoutanalysis** [comment]
Thank you! Works for me now.
