### ISSUE TITLE
module install repeatly each inject

### ISSUE THREAD

**Issue by khangvan** [ntsaini/node-red-contrib-function-npm#14]
Please check issue.
First require npm module to install
Second node-red inject to function then install process **repeat again.**
Could you modify to just install the first time, then second just verify only

**Comment by ntsaini** [comment]
@khangvan I am going to need more information. Could you detail the steps to reproduce? 

The node does not download on each inject. It will however download when you redeploy or restart the application. The node creates a temporary directory that is cleared after the application closes or when new code is deployed.

**Comment by khangvan** [comment]
Hi ntsaini,

Yes, you're right. I verify it's just download everfy **redeploy or restart**. So in console log create a long list install log because i use many node npm function cause i misunderstanded that repeated job.

Thank you for your support. I like to use this node function very much.

**Comment by ntsaini** [comment]
Glad you like it. Closing the issue now.
