### ISSUE TITLE
Keeping once installed modules

### ISSUE THREAD

**Issue by dgP86** [ntsaini/node-red-contrib-function-npm#16]
Hi,
when using the module in node-red and using a npm module the module will be installed and used. For my application the node-red module will not have access to the internet at all time, so whenever restarting node-red the required npm module will no longer be available and the flow will stop working.

Is there a way to have the npm module available permanently?

BR

**Comment by ntsaini** [comment]
No, not the way the module works currently. It creates a temp directory for node modules when the node-red application starts and then clears it off when the application is terminated.

node-red does provide a way to add modules permanently. Check out this [documentation](https://nodered.org/docs/writing-functions#loading-additional-modules). I think this method would work out better for you for offline access.

**Comment by dgP86** [comment]
Thanks for the feedback and the link, seems like I need to find a different approach.
