### ISSUE TITLE
May cause incorrect version of npm to be called

### ISSUE THREAD

**Issue by TotallyInformation** [ntsaini/node-red-contrib-function-npm#19]
Because this node has a dependency on a specific version of npm, it may cause issues because it doesn't match the version of node.js being used on the host system or the internals of npm may change without warning.

Please see https://stackoverflow.com/a/15957574/1309986

**Comment by ntsaini** [comment]
Thanks for opening these issues. I will have to think and research on how I want to address it. It might take a while as I try to find some free time. I would welcome a pull request if anyone else has a different way to address the issue.

**Comment by ntsaini** [comment]
Pushed out a new version, removed dependency on local npm module.
