### ISSUE TITLE
node-red-contrib-function-npm updated to slow when bindind to debug node

### ISSUE THREAD

**Issue by FadiBunni** [ntsaini/node-red-contrib-function-npm#2]
#I am trying to use Hx711 sensor for load cell. I managed to make it work, but this node is making the debug  console update too slow. I want it to update 4 times in a second but i am only allowed once in a second, even though if I use the trigger node to trigger every 250ms. 

Is it a function-npm problem, and how to fix it?

**Comment by ntsaini** [comment]
@FadiBunni Once the packages are loaded, there should be no delay in triggering the function. You will see a package loaded message in the status when you open your flow. I think most likely the source of delay might be somewhere else in your flow or may be in your function.

**Comment by ntsaini** [comment]
Closing this issue since I haven't received any feedback.
