### ISSUE TITLE
Using on node.js v12 may fail

### ISSUE THREAD

**Issue by TotallyInformation** [ntsaini/node-red-contrib-function-npm#20]
Due to the use of an old version of graceful-fs. v4.1.1

See also:

https://github.com/TotallyInformation/node-red-contrib-uibuilder/issues/72

**Comment by j2l** [comment]
I had the same issue due to `cb.apply is not a function`

**Comment by ntsaini** [comment]
Updated all dependencies, closing issue but feel free to open if still a problem.
