### ISSUE TITLE
Cache installed packages?

### ISSUE THREAD

**Issue by wormiedk** [ntsaini/node-red-contrib-function-npm#21]
Have you considered an option to keep the npm package between deploys?

**Comment by ntsaini** [comment]
Did think about it but didn't quite settle on how or if I wanted to do it. The node creates a random temp directory to store the module and wipes it off when the process close. To cache and reuse between restarts, I would have to store the location somewhere, or have it entered via configuration, which might result in more issues with security or file permissions. 

TBH I haven't devoted much time to this module recently. I know it needs a rewrite with different way to call npm and I am planning to get around to rewriting it, at that time I would definitely think about option to cache. I would welcome any suggestions or pull requests.

**Comment by ntsaini** [comment]
Updated the code so it keeps them installed in one temp directory. Still cleans it up when you close the node-red process.
