### ISSUE TITLE
Installation fails due to ENOENT: no such file or directory

### ISSUE THREAD

**Issue by beevelop** [ntsaini/node-red-contrib-function-npm#23]
```
"Error: ENOENT: no such file or directory, rename '/tmp/d-2019112-25-7ebysh.5rhw4/node_modules/seedrandom' -> '/tmp/d-2019112-25-7ebysh.5rhw4/node_modules/shuffle-seed/node_modules/seedrandom'"
```

Sometimes, when more than one install is running the following exception is thrown from the function-npm node.

**Comment by ntsaini** [comment]
Can you please paste "require" list portion of your code? Also what OS, node-red version and node version are you using?

**Comment by Bacto** [comment]
Hi,

First I would like to thank you for this awesome node!
It is a game changer to me!

I have the same problem on Node-RED 1.0.3:
`"Error: ENOENT: no such file or directory, rename '/tmp/d-2020324-19-1gdlmu4.6lre/node_modules/moment' -> '/tmp/d-2020324-19-1gdlmu4.6lre/node_modules/moment-timezone/node_modules/moment'"`

The required code is the following:
```javascript
const Influxdb = require('influxdb-v2@0.0.4');
const moment = require('moment@2.24.0');
const tz = require('moment-timezone@0.5.28');
```

**Comment by ntsaini** [comment]
I haven't been spending much time maintaining and developing this module lately. I know there are some fundamental issues in the way it uses the "npm" module in code. I keep telling myself, one day I will find the time to test the new code and publish but that target keeps moving in the future. I would suggest you check out the this [fork](https://github.com/neohelden/node-red-contrib-function-npm) in the meanwhile. I haven't personally tested the changes but look like that fork has updates that may work better.

**Comment by beevelop** [comment]
The only issue is, we don't have the fork published as of right now and it's therefore not available through the Node-RED palette. I'm happy to contribute the changes back upstream or take over maintenance if it helps :v:

**Comment by ntsaini** [comment]
Finally got to publish the new version, should work a lot better for multiple instances. Used the pull request code from @beevelop and added some modifications. That should solve these issues.

**Comment by beevelop** [comment]
Awesome @ntsaini. Thank you very much 🍻
