### ISSUE TITLE
Type Error : done is not a function

### ISSUE THREAD

**Issue by junoprima** [ntsaini/node-red-contrib-function-npm#27]
Hello i would try tutorial code but return error "TypeError: done is not a function"

It's return this error also when i not write anycode 

Version in use v0.4.1

![image](https://user-images.githubusercontent.com/29189180/88623350-faee8f00-d0ce-11ea-8c3c-3883604875ba.png)

**Comment by ntsaini** [comment]
@junoprima which version of node-red and nodejs are you using? I found a reference for the [change](https://nodered.org/blog/2019/09/20/node-done) done in node-red v1.0 onwards. Are you using pre v1.0 version of node-red?

**Comment by ntsaini** [comment]
Nevermind, I saw you mentioned v0.4.1. If its possible for you to update your node-red version > v1.0 it will solve your issue. As per the link send above seems node-red introduced this change after v1.0

**Comment by junoprima** [comment]
> @junoprima which version of node-red and nodejs are you using? I found a reference for the [change](https://nodered.org/blog/2019/09/20/node-done) done in node-red v1.0 onwards. Are you using pre v1.0 version of node-red? If you can update you node-red to >v1.0 I believe it will solve your issue.

Thank for reply i upgrade my nodered from 1.0 to 1.1.2 it's useful thank for help
