### ISSUE TITLE
Error : TypeError: upperCase is not a function

### ISSUE THREAD

**Issue by juangburgos** [ntsaini/node-red-contrib-function-npm#29]
Hi, thank you for this, but I cannot make it work. Using node-red v1.2.3 and node v12.19.0:

![func_error](https://user-images.githubusercontent.com/4707341/98662310-e1084d80-2347-11eb-948e-ecf1ebe6d479.gif)

**Comment by beevelop** [comment]
You are using the `upper-case` package wrong in this case. When using `require` instead of `import` (like stated in the README), the library does not directly expose the function.

```js
var uc = require("upper-case")
uc.upperCase('foobar')
```

https://npm.runkit.com/upper-case

**Comment by juangburgos** [comment]
Oh you are right, my bad, I thought the example on your README should without any modifications, but indeed if I use it as you say then it works. Thank you.
