### ISSUE TITLE
flow variables hangs node-red

### ISSUE THREAD

**Issue by theapu** [ntsaini/node-red-contrib-function-npm#7]
Using flow variables in function-npm crashes node-red. Are flow, context, global variables are supported?

**Comment by ntsaini** [comment]
Flow, context and global variables are supported. 

Can you provide details on the version of node-red, nodejs and operation system you are using? Also any other details on recreating the issue like does it happen when trying to use any variables or something specific.

**Comment by ntsaini** [comment]
Closing because of no response.
