### ISSUE TITLE
Node Repeatedly downloads same requires

### ISSUE THREAD

**Issue by arobinsongit** [ntsaini/node-red-contrib-function-npm#8]
I think this may have happened after installing on a new server with an updated version of node-red and node.js

9 Oct 22:08:26 - [info] Node-RED version: v0.19.4
9 Oct 22:08:26 - [info] Node.js  version: v10.11.0
9 Oct 22:08:26 - [info] Windows_NT 10.0.14393 x64 LE

+ lodash@4.17.11
added 1 package from 2 contributors in 3.508s
9 Oct 22:08:40 - [info] [function-npm:NPM Functions] Downloaded and installed NPM module: lodash
+ lodash@4.17.11
added 1 package from 2 contributors in 5.205s
9 Oct 22:08:41 - [info] [function-npm:NPM Functions] Downloaded and installed NPM module: lodash
+ xml2js@0.4.19
added 3 packages from 48 contributors in 5.41s
9 Oct 22:08:42 - [info] [function-npm:NPM Functions] Downloaded and installed NPM module: xml2js
+ xml2js@0.4.19
added 3 packages from 48 contributors in 5.829s
9 Oct 22:08:42 - [info] [function-npm:NPM Functions] Downloaded and installed NPM module: xml2js
+ xml2js@0.4.19
added 3 packages from 48 contributors in 6.077s
9 Oct 22:08:42 - [info] [function-npm:NPM Functions] Downloaded and installed NPM module: xml2js
+ xml2js@0.4.19
added 3 packages from 48 contributors in 6.336s
9 Oct 22:08:43 - [info] [function-npm:NPM Functions] Downloaded and installed NPM module: xml2js
9 Oct 22:09:06 - [info] Stopping flows
9 Oct 22:09:06 - [info] Stopped flows
9 Oct 22:09:06 - [info] Starting flows
9 Oct 22:09:06 - [info] Started flows

There is only a single instance of function-npm:NPM Functions and at the moment the code is actually commented out but it's still pulling the packages

/*
const xml2js = require('xml2js');
global.set('xml2js',xml2js);

const parseString = require('xml2js').parseString;
global.set('parseString',parseString);

const _ = require('lodash');
global.set('_',_);

const path = require('path');
global.set('path',path);

const mustache = require('mustache');
global.set('mustache',mustache);
*/
return msg;

Had been working fine on a different box for quite a while with no issues.

Also issues may have occured when started to run as a project instead of just a single flow but I'm not certain.

**Comment by arobinsongit** [comment]
NM - IO error

**Comment by ntsaini** [comment]
Could you explain a little bit more?
